# Generated by Django 3.0.1 on 2021-02-09 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loation', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('current_volume', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('current_volume', models.IntegerField()),
                ('installed_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_empty', models.BooleanField(default=True)),
                ('is_full', models.BooleanField(default=False)),
                ('last_operated_at', models.DateTimeField(auto_now=True)),
                ('last_operated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('store_management', 'Can manage oil storage and tank info'), ('store_keeping', 'Can record the storage info')],
            },
        ),
        migrations.CreateModel(
            name='StorageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=200)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('oil_volume', models.IntegerField(default=None)),
                ('delivered_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_branch', to='oilstorage.StorageBranch')),
                ('operated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_operator', to=settings.AUTH_USER_MODEL)),
                ('operated_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operated_tank', to='oilstorage.StorageTank')),
            ],
        ),
    ]
