# Generated by Django 3.0.1 on 2021-02-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagetank',
            name='current_volume',
            field=models.IntegerField(default=0),
        ),
    ]
