# Generated by Django 3.0.1 on 2021-02-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oilstorage', '0002_auto_20210211_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelog',
            name='delivered_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_branch', to='oilstorage.StorageBranch'),
        ),
        migrations.AlterField(
            model_name='storagelog',
            name='oil_volume',
            field=models.IntegerField(null=True),
        ),
    ]
