# Generated by Django 3.0.1 on 2021-02-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilstorage', '0003_auto_20210211_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebranch',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='storagetank',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
