# Generated by Django 3.0.1 on 2021-02-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilstorage', '0004_auto_20210213_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebranch',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='storagebranch',
            name='current_volume',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='storagelog',
            name='oil_volume',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='storagetank',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='storagetank',
            name='current_volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
