# Generated by Django 3.0.1 on 2021-02-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilstorage', '0005_auto_20210213_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebranch',
            name='current_volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
