# Generated by Django 3.0.1 on 2021-02-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oilstorage', '0006_auto_20210215_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagebranch',
            old_name='loation',
            new_name='location',
        ),
    ]
